// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbwstssxjogyvkazqpke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZid3N0c3N4am9neXZrYXpxcGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTk3MDQsImV4cCI6MjA1ODE5NTcwNH0.UmZvI9ZniB576PINbtLzQF-TuZMUXOiTmtvRv-oYq-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);